image: larsdroid/integratieproject1:v1

stages:
  - build
  - test
  - deploy

before_script:
  - echo "Start CI/CD"

build:
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
  only:
    - master

test:
  stage: test
  script: "mvn test"
  only:
    - master

deploy:
  stage: deploy
  script:
      - gcloud auth activate-service-account --key-file $GOOGLE_SERVICE_ACCOUNT_FILE
      - gcloud app deploy app.yaml --quiet --project $GOOGLE_PROJECT_ID
  only:
      - master

after_script:
  - echo "End CI/CD"