service: gcp-rest-demo-sample
runtime: java11
health_check:
  enable_health_check: false

handlers:
  - url: /.*
    script: this field is required, but ignored
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5
entrypoint: java -jar target/*.jar
